localStorage.setItem("Post Title", postTitle.innerHTML);
  	var downloadUrl = document.querySelectorAll(".safe");
  	function generateLink(){
      var generateBtn = document.querySelector(".generateBtn");
      var getlinkbtn = document.querySelector(".getlinkbtn");
      var downloaddiv = document.querySelector(".download-icon");
      var downloadbar = document.querySelector('.progress-bar');
      let width = 1;
      var downloadcounter = document.querySelector('#per')
      
      setInterval(() => {
                if (width >= 100) {
                    getlinkbtn.style.display = 'inline'
                    downloaddiv.style.display="none";
                    clearInterval();
                } else {
                    width++;
                    downloadbar.style.width = width + '%';
                    downloadcounter.innerHTML = width + '%';
                };
       }, postTime*10)
      downloaddiv.style.display="block";
      generateBtn.style.display="none";
   	}
  
   for (let i = 0; i < downloadUrl.length; i++) {
            const dlink = downloadUrl[i].href;
     		var uncodeurl = dlink.href = btoa(dlink);
     		downloadurlsafe = safepageurl + "?o=" + uncodeurl;
            function getLinkBtn(){
            window.open(downloadurlsafe, "_blank");
            }
        };
  	var er = document.querySelector(".safe");
	var dr = document.createElement('div');
	dr.innerHTML = er.innerHTML =`<div class="timerbtn">
        <div class="download-icon">
        <div class="divsvg">
      <p id="per">0%</p>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <g transform="rotate(0 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-1.8461538461538463s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(27.692307692307693 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-1.6923076923076923s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(55.38461538461539 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-1.5384615384615385s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(83.07692307692308 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-1.3846153846153846s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(110.76923076923077 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-1.2307692307692308s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(138.46153846153845 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-1.0769230769230769s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(166.15384615384616 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-0.9230769230769231s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(193.84615384615384 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-0.7692307692307693s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(221.53846153846155 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-0.6153846153846154s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(249.23076923076923 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-0.46153846153846156s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(276.9230769230769 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-0.3076923076923077s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(304.61538461538464 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="-0.15384615384615385s" repeatCount="indefinite"></animate>
      </rect>
    </g>
      <g transform="rotate(332.3076923076923 50 50)">
      <rect>
        <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="2s" begin="0s" repeatCount="indefinite"></animate>
      </rect>
    </g>
    <!-- [ldio] generated by https://loading.io/ --></svg></div>
    <div class="progress mx-auto mb-3" style="max-width:200px;margin: auto;">
          <div class="progress-bar progress-bar-striped progress-bar-animated jt-bg-primary"></div>
    </div>
</div>
        <button class="generateBtn" onclick="generateLink()">Download Now</button>
        <button class="getlinkbtn" onclick="getLinkBtn()">Get Link!</button>
        <p class="sapnaitgk" style="display:none;font-size:10px;padding:0;margin:0;">Powerd by 
        	<a href="https://www.sapnaitgk.com">SapnaITGK
  		</p>
    </div>`;
	er.parentNode.replaceChild(dr, er);
